name: tfm
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.7.7
  - pandas=1.1.1
  - numpy=1.19.1
  - matplotlib=3.3.1
  - joblib=0.16.0
  - scikit-learn=0.22.1
  - seaborn=0.10.1
  - altair=4.1.0
  - spacy=2.3.2
  - vega_datasets=0.8.0
  - requests=2.24.0
  - jupyterlab=2.2.6
  - notebook=6.1.1
  - requests
  - pip:
    - spotipy==2.14.0
    - lightgbm==3.0.0
    - beautifulsoup4
    - billboard.py
    - lyricsgenius==2.0.0
    - langdetect==1.0.8
    - streamlit==0.66.0